name: Node.js CI/CD with Docker

on: 
  workflow_dispatch: {}
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ["self-hosted"]

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t myproject-image:latest .

    - name: Create and Set Environment Variables
      run: |
        echo "${{ secrets.PROD_Secrets }}" > .env
      env:
        PROD_Secrets: ${{ secrets.PROD_Secrets }}

    - name: Restart Docker container
      run: |
        docker stop myproject-container || true
        docker rm myproject-container || true
        docker run -d --name myproject-container \
          --env-file .env \
          -p 3001:3001 myproject-image:latest
